name: Build

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    name: Deploy Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install mkdocs-material
      - run: cd docs && mkdocs gh-deploy --force
